[package]
name = "rust_dev"
version = "0.1.0"
edition = "2021"
default-run = "rust_dev"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
toml = "0.5"
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "sqlite", "macros"] }
dotenv = "0.15"

[dependencies.syn]
version = "1.0"
features = ["parsing", "proc-macro", "printing", "derive"]